### PR TITLE
ts-web: testing set runtime version in network fixture

### PR DESCRIPTION
**Pull request by pro-wh**
otherwise it expects 0.0.0 and none of the nodes launch the runtime

regressed in #915

### CODE REVIEW

**Comment by pro-wh** [comment]
nope still spinning

**Comment by pro-wh** [comment]
image

:angry: why ci gotta be like that

**Comment by pro-wh** [comment]
image

it even passes, but why doesn't the step complete

**Comment by pro-wh** [comment]
tried running it locally, and it didn't hang there

**Comment by pro-wh** [comment]
I noticed that the video capture was going at 0.05 fps so I tried disabling that. now it finishes. gonna add a commit to disable that throughout. we don't even upload the videos.

re-enable locally for local testing, although I suppose you'd sooner use `cypress open` in that case

**Comment by pro-wh** [comment]
same problem with benchmark-rt. I'm going to disable that for now. if anyone wants to have it start running again, make changes similar to how sample-run-network patches the fixture. or maybe make the net runner work on its own again, that'd be neat

**Review by Yawning — APPROVED** [review]

**Review by ptrus — APPROVED** [review]

**Comment by Yawning** [comment]
I'm just merging this now, because this issue is blocking other stuff.

**Pull request merged**
