### PR TITLE
evm: Implement call_format precompile

### PR DESCRIPTION
**Pull request by matevz**
TODO

### CODE REVIEW

**Comment by nhynes** [comment]
What kind of app needs to know the callformat? It seems like something the contract either shouldn't care about, and if it does, it should let the user specify the desired behavior rather than inferring it from something that happens outside of the contract's universe.

**Comment by matevz** [comment]
> What kind of app needs to know the callformat? It seems like something the contract either shouldn't care about, and if it does, it should let the user specify the desired behavior rather than inferring it from something that happens outside of the contract's universe.

Two reasons actually:
1. consistency with [Cipher's context object](https://github.com/oasisprotocol/oasis-sdk/blob/main/contract-sdk/src/context.rs) 
2. since encrypted transactions are not enforced, a way for dApp devs to make sure no private data is leaked by (accidentally?) unencrypted calls and transactions.

**Comment by nhynes** [comment]
> consistency with Cipher's context object

We don't need consistency with an experimental ParaTime.

> since encrypted transactions are not enforced, a way for dApp devs to make sure no private data is leaked by (accidentally?) unencrypted calls and transactions.

I call using the encrypting cipher and then publish the results online. You can't stop people from compromising themselves. You have to go out of your way to use the plain cipher, so it's clearly intentional. The contract should be programmed not to release secrets to people who are going to compromise themselves.

**Comment by matevz** [comment]
Superseeded by https://github.com/oasisprotocol/emerald-web3-gateway/pull/340

**Pull request closed without merging**
