### PR TITLE
ts-web/rt tests with keyvalue runtime

### PR DESCRIPTION
**Pull request by pro-wh**
uses #37, cc @abukosek

### CODE REVIEW

**Comment by pro-wh** [comment]
can't get the testnet to work. pls help

**Comment by pro-wh** [comment]
this now runs locally. something's getting tied up in initialization or something, with the first `insert` call taking ~25 seconds.

might have some issue running on CI, because when I run it locally, it fails for a while with `client: not finished initial sync`. will need to add a wait for that

**Comment by kostko** [comment]
> this now runs locally. something's getting tied up in initialization or something, with the first insert call taking ~1 minute.

That's normal as it requires some initial epoch transitions to set up committees.

**Comment by pro-wh** [comment]
getting stream reset from client-0's internal.sock on the first WaitReady call, according to envoy. but client-0's logs say it never even received a request. can't reproduce this locally.

**Comment by pro-wh** [comment]
seemed to be a CORS thing. the cypress test was pointed at the wrong port. dunno why it worked locally though

**Review by kostko — APPROVED** [review]
The test key value runtime needs some fixes as indicated in the other PR. But let's merge this so we have some E2E tests.

**Comment by pro-wh** [comment]
thanks, I'll rebase

**Pull request merged**
