### PR TITLE
tests: fix syntax difference with single-dependency modules

### PR DESCRIPTION
**Pull request by pro-wh**
modules that only have one dependency get rewritten without the parentheses, so we can't look for a verbatim line match

I guess we'll start writing our own parser then :roll_eyes:

### CODE REVIEW

**Comment by kostko** [comment]
You can convert back to draft.

**Comment by kostko** [comment]
It's slightly hidden though, do you not see this:
image

**Comment by pro-wh** [comment]
oh thanks, I hadn't noticed that

**Comment by pro-wh** [comment]
ok I've reimplemented this in awk

**Review by kostko — APPROVED** [review]

**Pull request merged**
