### PR TITLE
ts-web/core: 0.1.0-alpha8

### PR DESCRIPTION
**Pull request by pro-wh**
with the new grpc client error wrapping

### CODE REVIEW

**Comment by pro-wh** [comment]
gonna hold off for one more tweak to the error wrapping

**Comment by pro-wh** [comment]
that error handling thing is long merged. opening this up for review

**Review by kostko — APPROVED** [review]

**Comment by pro-wh** [comment]
proceeding to merge and release

**Comment by pro-wh** [comment]
audit failed due to some lru issue, but that should be unrelated

benchmark thing failed, but that's known to be flaky

**Comment by pro-wh** [comment]
https://www.npmjs.com/package/@oasisprotocol/client/v/0.1.0-alpha8

**Pull request merged**
