### PR TITLE
grpc error details, protobufjs variant

### PR DESCRIPTION
**Pull request by pro-wh**
this other library has a smaller bundle size impact

image

also typescript declarations :heart_eyes:

### CODE REVIEW

**Comment by pro-wh** [comment]
error preview 
image

**Comment by pro-wh** [comment]
npm goes in alphabetical order and not topological order :skull:

**Comment by pro-wh** [comment]
here's me putting the proto stuff outside of src

**Review by kostko — APPROVED** [review]

**Comment by pro-wh** [comment]
gotta add the compiled proto to the package.json `files` list

**Comment by pro-wh** [comment]
oh also adding changelog

**Pull request merged**
